linters:
  disable-all: false

service:
  golangci-lint-version: 1.41

run:
  skip-dirs:
    - gov/simulation
    - gov/client
    - simulation

  skip-files:
    - _test.go
    
issues:
  new: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false