name: CI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: "Build binaries"
        run: make build

      - name: "Run lint"
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.41
          args: --timeout=10m
          only-new-issues: true

      - name: "Run tests"
        run: make tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./cover.out
